"""
Product Intelligence Review UI — Streamlit app.

Shows every extracted product record, highlights low-confidence fields,
and lets a reviewer approve or flag each attribute.

Run with:
    streamlit run review_ui.py
"""

import json
import os
import glob
import streamlit as st

OUTPUT_DIR = "data/output"

CONFIDENCE_COLOR = {
    "high": "🟢",
    "medium": "🟡",
    "low": "🔴",
}

STATUS_COLOR = {
    "ok": "🟢",
    "incomplete": "🟡",
    "needs_review": "🔴",
}


def load_records():
    """Load all JSON records from the output directory."""
    files = sorted(glob.glob(os.path.join(OUTPUT_DIR, "*.json")))
    records = []
    for path in files:
        try:
            with open(path) as f:
                data = json.load(f)
            data["_file"] = os.path.basename(path)
            records.append(data)
        except Exception:
            pass
    return records


def render_attribute_table(attributes: list[dict]):
    """Render attributes as a colour-coded table with source snippets."""
    if not attributes:
        st.info("No attributes extracted.")
        return

    low_conf = [a for a in attributes if a.get("confidence") == "low"]
    if low_conf:
        st.warning(f"{len(low_conf)} attribute(s) flagged low-confidence — review carefully.")

    for attr in attributes:
        conf = attr.get("confidence", "?")
        icon = CONFIDENCE_COLOR.get(conf, "⚪")
        needs_review = attr.get("needs_review", False)
        review_badge = " ⚠️" if needs_review else ""

        with st.expander(f"{icon} **{attr['name']}** = {attr['value']}"
                         + (f" {attr.get('unit', '')}" if attr.get("unit") else "")
                         + review_badge):
            st.markdown(f"**Confidence:** {conf}")
            st.markdown(f"**Source:** `{attr.get('source_id', '?')}`")
            st.markdown(f"**Evidence:**")
            st.info(attr.get("source_snippet", "—"))
            if attr.get("needs_review"):
                st.error("Flagged for human review (low confidence)")


def main():
    st.set_page_config(page_title="Product Intelligence Review", layout="wide")
    st.title("Product Intelligence — Review UI")
    st.caption("Generated by AI extraction pipeline · Low confidence = 🔴 · Needs review = ⚠️")

    records = load_records()

    if not records:
        st.warning(
            f"No output files found in `{OUTPUT_DIR}/`. "
            "Run `python pipeline.py` first to generate records."
        )
        return

    # Sidebar: product selector
    product_names = [
        f"{STATUS_COLOR.get(r.get('validation', {}).get('overall_status', ''), '⚪')} "
        f"{r.get('record', {}).get('product_name', r['_file'])}"
        for r in records
    ]
    st.sidebar.header(f"Products ({len(records)})")
    selected_idx = st.sidebar.radio("Select product", range(len(records)),
                                    format_func=lambda i: product_names[i])

    data = records[selected_idx]
    rec = data.get("record", {})
    val = data.get("validation", {})

    # Header
    col1, col2, col3 = st.columns([3, 1, 1])
    with col1:
        st.header(rec.get("product_name", "Unknown"))
        if rec.get("manufacturer"):
            st.caption(f"Manufacturer: {rec['manufacturer']}")
        if rec.get("category"):
            st.caption(f"Category: {rec['category']}")
        if rec.get("model_numbers"):
            st.caption(f"Models: {', '.join(rec['model_numbers'])}")

    with col2:
        score = val.get("completeness_score", 0)
        st.metric("Completeness", f"{score*100:.0f}%")

    with col3:
        status = val.get("overall_status", "?")
        st.metric("Status", f"{STATUS_COLOR.get(status, '')} {status.upper()}")

    if rec.get("short_description"):
        st.markdown(f"> {rec['short_description']}")

    st.divider()

    # Validation issues
    missing = val.get("missing_fields", [])
    conflicts = val.get("conflicts", [])
    if missing:
        st.warning(f"**Missing expected fields:** {', '.join(missing)}")
    if conflicts:
        for c in conflicts:
            st.error(f"**Conflict:** {c}")

    # Sources
    sources = rec.get("sources", [])
    if sources:
        with st.expander("Sources"):
            for s in sources:
                st.markdown(f"- `{s}`")

    st.subheader(f"Extracted Attributes ({len(rec.get('attributes', []))})")
    render_attribute_table(rec.get("attributes", []))

    # Raw JSON toggle
    with st.expander("Raw JSON"):
        st.json(data)


if __name__ == "__main__":
    main()
